#!/usr/bin/env bash
# vim: filetype=sh
# vim: syntax=sh

#------Setup display----------------------------------#
# currently using only one display at a time
for m in $(xrandr | rg ' connected' | cut -f1 -d' '); do
	if [[ "$m" == HDMI* ]]; then
		active="$m"
	elif [[ "$m" == VGA* ]] && ! [[ "$active" == HDMI* ]]; then
		active="$m"
	elif [[ "$m" == eDP* ]] || [[ "$m" == LVDS* ]]; then
		active="$m"
	else 
		echo "don't know which display to use!"
	fi
done

bspc monitor "$active" -d a b c d e f g h i j

#------Source colours from pywal----------------------#
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

#------Layout settings--------------------------------#
bspc config border_with			4
bspc config window_gap			6

# Padding
bspc config bottom_padding		2
bspc config top_padding			30
bspc config left_padding		2
bspc config right_padding		2

bspc config split_ratio			0.50

bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config paddingless_monocle		true
bspc config single_monocle		false

#------Basic behaviour--------------------------------#
bspc config initial_polarity		second_child;
bspc config directional_focus_tightness high;

bspc config focus_follows_pointer	true

#------Rules------------------------------------------#
bspc rule -r *:*

#------Startup----------------------------------------#
! pgrep -x "polybar" > /dev/null && select_polybar_config load
! pgrep -x "sxhkd" > /dev/null && sxhkd &

startup.sh
