#!/usr/bin/env bash
echo
colordir="$DOTFILES/colors"
filepath="$colordir/.active.theme"
if [ -n "$1" ]; then
	if [ -e "$colordir/$1" ]; then
		xrdb -load "$colordir/$1"
		palette
		theme=$1
		if [ -e "$filepath" ]; then 
			rm "$filepath"
		fi

		echo $theme >> $filepath
		
		echo -e "\e[31m\e[1mYour \e[32mtheme \e[33mis \e[34mnow \e[35mset \e[36mto \e[5m\e[39m$theme"
	elif ! [ -e "$colordir/$1" ]; then
		echo -e "Are you sure you meant to type \e[35m$1?"
	fi
else
	if [ -e "$filepath" ]; then
		while read -r line
		do
			theme="$line"
		done < "$filepath"
	fi
	echo "$theme"
fi
echo
