# Example ~/.zsh/plugins.toml file
# --------------------------------

# Global matches, if a plugin doesn't provide a `use` field then the first one
# of the following that matches more than zero files will be used.
match = [
  '{{ name }}.zsh',
  '*.zsh',
  '*.sh',
]

# Global templates to apply by default, if a plugin doesn't provide an `apply`
# field then these will be used.
apply = ['PATH', 'source']

# Custom user defined templates, the `each` field means that these will be
# applied for all matched files.
[templates]
function = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/{{ name }}"', each = true }
prompt = { value = 'ln -sf "{{ filename }}" "{{ root }}/functions/prompt_{{ name }}_setup"', each = true }

[plugins.async]
# `github` sources provide the repository in the form {username}/{repository}.
github = 'mafredri/zsh-async'
# All plugins can specify the template names that will be applied.
apply = ['function']

[plugins.aliases]
local = '~/.cross-shell-plugins'

[plugins.zsh-specific]
local = '~/.zsh/plugins'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'
